import PDFDocument from "pdfkit";

export default async function buildSummaryPDF(data, res) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");

  doc.pipe(res);

  // Header
  doc.image("assets/logo.png", 50, 30, { width: 70 });
  doc.fontSize(20).fillColor("#1177bb").text("EV Rental Report", 130, 40);

  doc.moveDown(2);

  // KPI Section
  doc.fontSize(14).text("Key Metrics", { underline: true });

  const { metrics } = data;

  doc.fontSize(12).text(`
  Total Vehicles: ${metrics.total_vehicles}
  Registered Customers: ${metrics.registered_customers}
  Rentals Today: ${metrics.today_rentals}
  Staff Count: ${metrics.staff_count}
  `);

  doc.moveDown(2);

  // Table
  doc.fontSize(14).text("Details Table", { underline: true });

  data.table.forEach(row => {
    doc.fontSize(12).text(`${row.label}: ${row.value}`);
  });

  // Footer
  doc.moveTo(50, 750).lineTo(550, 750).stroke("#1177bb");
  doc.fontSize(10).text("Generated by EV Gateway", 50, 760);

  doc.end();
}
